apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election-operator

---
apiVersion: v1
kind: Pod
metadata:
  name: leader-election-operator-1
spec:
  serviceAccountName: leader-election-operator
  containers:
    - name: operator
      image: leader-election-operator
      imagePullPolicy: Never
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-admin
subjects:
  - kind: ServiceAccount
    name: leader-election-operator
roleRef:
  kind: ClusterRole
  name: leader-election-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leader-election-operator
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "sample.javaoperatorsdk"
    resources:
      - leaderelectiontestcustomresources
      - leaderelectiontestcustomresources/status
    verbs:
      - '*'
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      -  "leases"
    verbs:
      - '*'

