apiVersion: v1
kind: Pod
metadata:
  name: leader-election-operator-2
spec:
  serviceAccountName: leader-election-operator
  containers:
    - name: operator
      image: leader-election-operator
      imagePullPolicy: Never
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
