apiVersion: v1
kind: Service
metadata:
  name: ""
  ownerReferences: # used for finding which Tomcat does this Deployment belong to
    - apiVersion: apps/v1
      kind: Tomcat
      name: ""
      uid: ""
spec:
  selector:
    app: ""
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
