apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webpages.sample.javaoperatorsdk
spec:
  group: sample.javaoperatorsdk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                html:
                  type: string
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                htmlConfigMap:
                  type: string
                areWeGood:
                  type: string
                errorMessage:
                  type: string
      subresources:
        status: { }
  scope: Namespaced
  names:
    plural: webpages
    singular: webpage
    kind: WebPage
    shortNames:
      - wp
