apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webservers.sample.javaoperatorsdk
spec:
  group: sample.javaoperatorsdk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                html:
                  type: string
            status:
              type: object
              properties:
                htmlConfigMap:
                  type: string
                areWeGood:
                  type: string
      subresources:
        status: { }
  scope: Namespaced
  names:
    plural: webservers
    singular: webserver
    kind: WebServer
    shortNames:
      - ws
