apiVersion: v1
kind: ServiceAccount
metadata:
  name: webpage-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-operator
spec:
  selector:
    matchLabels:
      app: webpage-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: webpage-operator
    spec:
      serviceAccountName: webpage-operator
      containers:
      - name: operator
        image: webpage-operator
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /startup
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 2
          failureThreshold: 3

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-admin
subjects:
- kind: ServiceAccount
  name: webpage-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: webpage-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webpage-operator
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - services
  - configmaps
  - pods
  verbs:
  - '*'
- apiGroups:
  - "apps"
  resources:
  - deployments
  - services
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "sample.javaoperatorsdk"
  resources:
  - webpages
  - webpages/status
  verbs:
  - '*'
- apiGroups:
    - "networking.k8s.io"
  resources:
    - ingresses
  verbs:
    - '*'

