#
# Copyright Java Operator SDK Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Custom Resource Definition that will be used to generate the Java classes in target/generated-sources/java
# See https://github.com/fabric8io/kubernetes-client/blob/master/doc/java-generation-from-CRD.md
# The Java classes will then be used to recreate this CR in target/classes/META-INF/fabric8
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: leaderelections.sample.operator.javaoperatorsdk.io
spec:
  group: sample.operator.javaoperatorsdk.io
  names:
    kind: LeaderElection
    singular: leaderelection
    plural: leaderelections
    shortNames:
    - le
    - les
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              reconciledBy:
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
