---

# Site settings
name: Java Operator SDK
title: Java Operator SDK
description:            Build Kubernetes Operators in Java without hassle
logo:                   logo-white.svg
logo-icon:              logo-icon.svg
permalink:              /:title/
date_format:            "%b %-d, %Y"
images:                /assets/images/


# Rouge highlighter
markdown: kramdown
highlighter: rouge

kramdown:
  parse_block_html: true
  permalink: /:title
  syntax_highlighter_opts:
     disable : true

plugins:
  - "jekyll-github-metadata"
