name: Build with Kubernetes

env:
  MAVEN_ARGS: -V -ntp -e

on:
  workflow_call:
    inputs:
      kube-version:
        type: string
        required: true

jobs:
  integration_tests:
    strategy:
      matrix:
        java: [ 17, 21 ]
    uses: ./.github/workflows/integration-tests.yml
    with:
      kube-version: ${{ inputs.kube-version }}
      java-version: ${{ matrix.java }}
