name: Build with Kubernetes

env:
  MAVEN_ARGS: -V -ntp -e

on:
  workflow_call:

jobs:
  integration_tests:
    strategy:
      matrix:
        java: [ 17, 21, 25 ]
        # Use the latest versions supported by minikube, otherwise GitHub it will
        # end up in a throttling requests from minikube and workflow will fail.
        # Minikube does such requests only if a version is not officially supported.
        kubernetes: [ '1.30.12', '1.31.8', '1.32.4','1.33.1' ]
    uses: ./.github/workflows/integration-tests.yml
    with:
      java-version: ${{ matrix.java }}
      kube-version: ${{ matrix.kubernetes }}

  httpclient-tests:
    strategy:
      matrix:
        httpclient: [ 'vertx', 'jdk', 'jetty' ]
    uses: ./.github/workflows/integration-tests.yml
    with:
      java-version: 25
      kube-version: '1.32.0'
      http-client: ${{ matrix.httpclient }}
      experimental: true

  special_integration_tests:
    name: "Special integration tests (${{ matrix.java }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21, 25 ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Java and Maven
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Run Special Integration Tests
        run: ./mvnw ${MAVEN_ARGS} -B package -P minimal-watch-timeout-dependent-it --file pom.xml
