name: Fabric8 Client Snapshot Build

env:
  MAVEN_ARGS: -V -ntp -e

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
on:
  schedule:
    #   Run on end of the day
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  check_format_and_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'fabric8-next-version'
      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Run unit tests
        run: ./mvnw ${MAVEN_ARGS} clean install --file pom.xml -Dhighest-basedir=$PWD

  build:
    uses: ./.github/workflows/build.yml